// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAogYo6k1e_s5_NGmmN0kDsxxopd2nqjjQ',
    appId: '1:439672808351:web:502c949af15b013ba353aa',
    messagingSenderId: '439672808351',
    projectId: 'crony-7fada',
    authDomain: 'crony-7fada.firebaseapp.com',
    storageBucket: 'crony-7fada.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIXUmPDHlagnArlwWW82ZKX4VfhM3pnuA',
    appId: '1:439672808351:android:b5c28889c23ba6b4a353aa',
    messagingSenderId: '439672808351',
    projectId: 'crony-7fada',
    storageBucket: 'crony-7fada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmza71I_DTClnK7EuAV8Fe_OwfRMCGBLs',
    appId: '1:439672808351:ios:7d1688a66e89bae2a353aa',
    messagingSenderId: '439672808351',
    projectId: 'crony-7fada',
    storageBucket: 'crony-7fada.firebasestorage.app',
    androidClientId: '439672808351-q9acigalsd697r4ahq29pa0aq9dvpma1.apps.googleusercontent.com',
    iosClientId: '439672808351-pfukdui05o0q6b5uo3tfi0erep1gsg1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.crony',
  );

}